# Generated by Django 2.0 on 2017-12-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('language', models.CharField(blank=True, max_length=5)),
                ('copyright', models.CharField(blank=True, max_length=255)),
                ('managing_editor', models.EmailField(blank=True, help_text='Email address for person responsible for editorial content.', max_length=254)),
                ('web_master', models.EmailField(blank=True, help_text='Email address for person responsible for technical issues relating to channel.', max_length=254)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('last_build_date', models.DateTimeField(blank=True, null=True)),
                ('ttl', models.PositiveIntegerField(blank=True, help_text='The number of minutes a channel can be cached before refreshing.', null=True, verbose_name='TTL')),
                ('generator', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('redirect', models.URLField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('itunes', models.URLField(blank=True, verbose_name='iTunes Store URL')),
                ('block', models.BooleanField(default=False, help_text='Block this podcast on iTunes.')),
            ],
        ),
    ]
